### PR TITLE
Update rfp-014-private-retrieval-of-data.md

### PR DESCRIPTION
**Pull request by AvishayYanay**
Adding Blinder to the reading list, as it implements a reverse-PIR (namely, PIW) which can be similarly used for PIR.

### CODE REVIEW

**Comment by willscott** [comment]
This list isn't meant to be extensive, which would be impossible, but rather provide a basic sense of the areas that this call is interested in.

PIW/PIS is interesting, and the hope was that it would be captured by the mentioned Express work.

Blinder and extensions of that work are relevant here, and there is interest in the ability to combine these forms, as blinder does with MPC + PIW.

**Comment by AvishayYanay** [comment]
It's just a suggestion, please do whatever you think is best :)

**Review by willscott — APPROVED** [review]
This is relevant as is the private set intersection work you've done

**Review by jsoares — APPROVED** [review]

**Comment by jsoares** [comment]
Thanks, @AvishayYanay !

**Pull request merged**
