### PR TITLE
RFP-014: Private Retrieval of Data

### PR DESCRIPTION
**Pull request by asilinphoto**
Forked repository. Pull request to create RFP-014

### CODE REVIEW

**Comment by asilinphoto** [comment]
Marked up from [Google Doc here](https://docs.google.com/document/d/1IAB86MvWXcf_V2MDCCjE3UOEzXP-KGT-uwnkhtYXgaA/edit#)

**Comment by jsoares** [comment]
I'm confused: why did you fork? You have permissions to create branches in this repo...

Also, you edited RFP-012 instead of creating a new file. I'll fix it in my next commit.

**Review by jsoares — APPROVED** [review]
lgtm; let's merge given time constraints and get a review from Will

**Comment by asilinphoto** [comment]
@jsoares 
> I'm confused: why did you fork? You have permissions to create branches in this repo...
> 
> Also, you edited RFP-012 instead of creating a new file. I'll fix it in my next commit.

I create forks when I'm not entirely comfortable with what I'm doing. In the fork I create a branch from, in this case, the previous RFP then create a pull request. The last time I created a new file directly it triggered the bug so I'm not really comfortable editing without forks

**Pull request merged**
