### PR TITLE
Create RFP-10

### PR DESCRIPTION
**Pull request by jsoares**

### CODE REVIEW

**Comment by jsoares** [comment]
Should we move to 3-digit RFP numbers (e.g. RFP-010) to keep folder sorting consistent? There are very few references outside this repo so should be easy to make the change.

**Comment by KarolaKirsanow** [comment]
I considered re-doing the numbering  when I opened this branch. Changing file names may break any direct links, but I suspect they are few.

The question then becomes "do we go straight to double-0 numbering?"

**Comment by jsoares** [comment]
> I considered re-doing the numbering when I opened this branch. Changing file names may break any direct links, but I suspect they are few.
> 
> The question then becomes "do we go straight to double-0 numbering?"

Yeah, I think we can fix them. I checked the website quickly and didn't see any direct links (we've also been careful because of broken links once program closes). There are some internal links in GitHub but those are easy to fix.

As for the 3-digit, better to future proof? 🤷

**Review by KarolaKirsanow — APPROVED** [review]
lgtm. agnostic as to whether renumbering is necessary for this PR

**Pull request merged**
